### ISSUE TITLE
python 2.7 SyntaxError

### ISSUE THREAD

**Issue by Sidaartha** [RedisJSON/redisjson-py#41]
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rejson/__init__.py", line 124, in <module>
    from .client import Client
  File "/Library/Python/2.7/site-packages/rejson/client.py", line 106
    def jsonget(self, name, *args, no_escape=False):
                                           ^
SyntaxError: invalid syntax
```

In Python 2, all positional arguments must come before any *args argument.

**Comment by gkorland** [comment]
@Sidaartha you can use this #42 PR (branch fix_2_7), but if we merge it we'll create a backward issue, see the failed test on the PR
